del *.__i /s
del *.axf /s
del *.bak /s
del *.crf /s
del *.d /s
del *.ddk /s
del *.dep /s
del *.dot /s
del *.edk /s
del *.hex /s
del *.htm /s
del *.iex /s
del *.lnp /s
del *.lst /s
del *.map /s
del *.mpf /s
del *.mpj /s
del *.o /s
del *.obj /s
del *.omf /s
del *.plg /s
del *.rpt /s
del *.sct /s
del *.tmp /s
del *.tra /s
del *.uvguix.* /s
del *.mxproject /s
del JLinkLog.txt /s